_target_: discrete_diffusion.algorithms.ar.AR
name: ar
backbone: dit
parameterization: ar
time_conditioning: False
causal_attention: True
# Irrelevant flags
T: 0
ignore_bos: False
sampler:
  _target_: discrete_diffusion.sampling.ar.ARSampler
