samples_path: ???  # Required: path to samples (.pt, .npz, .json)
model_tokenizer: gpt2  # Tokenizer used by diffusion model to generate samples
pretrained_model: google/gemma-2-9b  # Eval LM
batch_size: 4
max_length: 512
retokenize: true       # Re-tokenize with eval model's tokenizer
first_chunk_only: true # Evaluate only up to first EOS
metrics_path: gen_ppl_metrics.json
torch_compile: false

