predictor: ddpm_cache
steps: 5000
use_float64: False
p_nucleus: 1.0
num_sample_batches: 1
num_sample_log: 2
semi_ar: True
stride_length: 1
num_strides: 1
inject_bos: True
first_hitting: True
kv_cache: False
var_length: False
sampler:
  _target_: discrete_diffusion.sampling.uniform.UniformSampler
