_target_: src.discrete_diffusion.utils.CosineDecayWarmupLRScheduler
t_in_epochs: False
t_initial: ${sub:${trainer.max_steps}, ${.warmup_t}}
warmup_prefix: True
warmup_lr_init: 1e-6
warmup_t: ${mul:0.1, ${trainer.max_steps}}
lr_min: 1e-6
